name: data
on:
  schedule:
    - cron: 0 0 1 * *
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat.yml
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.10.x
      - name: Check out repo
        uses: actions/checkout@v2
      - name: "Create axios config"
        env: 
          COOKIE: ${{ secrets.COOKIE }}
        run: |
              mkdir tmp;echo "{ \"headers\": {  \"Cookie\": \"session=$COOKIE\" } }" > /tmp/query.json
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://adventofcode.com/2022/leaderboard/private/view/2473134.json
          downloaded_filename: aoc_hw_tech_club_private_leaderboard.json
          axios_config: /tmp/query.json
